global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'kyc-api'
    static_configs:
      - targets: ['api:8080']

  - job_name: 'kyc-worker'
    static_configs:
      - targets: ['worker:8080'] 